apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-test-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Thunberg087/web-test-config
    path: app
    targetRevision: main
    helm:
      valueFiles:
        - envs/prod/values.yaml
        - envs/prod/version.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true